# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_tsne <- function(indices, distances, init, iter, max_depth, lie_iter, mom_iter, leaf_approx, num_threads) {
    .Call('_qdtsne_run_tsne', PACKAGE = 'qdtsne', indices, distances, init, iter, max_depth, lie_iter, mom_iter, leaf_approx, num_threads)
}

